# BEGIN ACE
[colors.bright]
black = "#281c1f"
red = "#55929E"
green = "#4D9CB4"
yellow = "#6398DD"
blue = "#98A1AB"
magenta = "#C3C0B7"
cyan = "#B1CAD7"
white = "#e1e7ea"

[colors.cursor]
cursor = "#e1e7ea"
text = "#281c1f"

[colors.normal]
black = "#281c1f"
red = "#55929E"
green = "#4D9CB4"
yellow = "#6398DD"
blue = "#98A1AB"
magenta = "#C3C0B7"
cyan = "#B1CAD7"
white = "#e1e7ea"

[colors.primary]
background = "#281c1f"
foreground = "#e1e7ea"
# END ACE

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true

[window]
opacity = 0.9

[window.padding]
x = 30
y = 30
