#! /bin/sh

#
#                 ░█▀▄░█▀▀░█▀█░█░█░█▄█
#                 ░█▀▄░▀▀█░█▀▀░█▄█░█░█
#                 ░▀▀░░▀▀▀░▀░░░▀░▀░▀░▀
#

# ----------------------
# THEME
# ----------------------

# Get a random wallpaper
# WALLPAPER=`~/.scripts/get_rand_wallpaper.sh`
# WALLPAPER=~/Pictures/wallpapers/hololive/ayame_sword.png
WALLPAPER=~/Pictures/wallpapers/other/capybara.jpg

# Colorschemes + wallpaper
~/.scripts/wal_complete.sh -i $WALLPAPER

# ----------------------
# CONFIG
# ----------------------

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd & # Hotkey daemon
~/.config/polybar/launch.sh # Bar
picom & # Compositor
~/.config/dunst/launch.sh & # Notifications

# Workspaces
bspc monitor -d 一 二 三 四 五

# Bspwm config
bspc config border_width 2
bspc config window_gap 5
bspc config split_ratio 0.6

# Sound (on gentoo)
# ~/.scripts/start_pipewire.sh &

# Fix java apps
export _JAVA_AWT_WM_NONREPARENTING=1

# Default editor
export EDITOR='nvim'

# Colorschemes + wallpaper
WALLPAPER=~/Pictures/wallpapers/hololive/ayame_sword.png
~/.scripts/wal_complete.sh -i $WALLPAPER

# Faster keyboard retype
xset r rate 250 45

# Startup apps
./.startup_apps.sh &

# Rules
bspc config ignore_ewmh_focus true # Don't change workspace on app startup
bspc config pointer_motion_interval 7 # 144hz floating window
bspc rule -a Alacritty:Alacritty state=tiled
bspc rule -a gl:mpv state=fullscreen
bspc rule -a pulsemixer state=floating
bspc rule -a firefox desktop='^3'
bspc rule -a discord desktop='^2'
bspc rule -a Org.gnome.Nautilus rectangle=800x800 state=floating
bspc rule -a cool-retro-term state=fullscreen
bspc rule -a Ymuse state=floating

# ----------------------
# MISC
# ----------------------

export EDITOR='nvim'

# Faster keyboard retype
xset r rate 250 45

# Startup apps
./.startup_apps.sh

exec bspwm
