#! /bin/sh

#
#                 ░█▀▄░█▀▀░█▀█░█░█░█▄█
#                 ░█▀▄░▀▀█░█▀▀░█▄█░█░█
#                 ░▀▀░░▀▀▀░▀░░░▀░▀░▀░▀
#

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd & # Hotkey daemon
~/.config/polybar/launch.sh # Bar
picom & # Compositor
~/.config/dunst/launch.sh & # Notifications

# Workspaces
bspc monitor -d 一 二 三 四 五

bspc config border_width 2
bspc config window_gap 5
bspc config split_ratio 0.6

# Rules
bspc rule -a firefox desktop=^2
bspc rule -a Alacritty desktop=^1 state=pseudo_tiled
bspc rule -a org.gnome.Nautilus desktop=^1 state=pseudo_tiled
bspc rule -a cool-retro-term desktop=^3 state=fullscreen
